- name: Configure CNI network
  hosts: masters
  become: yes
  tasks:
    - name: Download calico.conf
      get_url:
        url: "https://raw.githubusercontent.com/Solnijko/kubernetes-configs/main/calico.conf"
        dest: /etc/NetworkManager/conf.d/
        validate_certs: no
    
    - name: Install the Tigera Calico operator and custom resource definitions
      shell: |
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/tigera-operator.yaml
    
    - name: Apply custom resources
      shell: |
        kubectl create -f https://raw.githubusercontent.com/Solnijko/kubernetes-configs/main/custom-resources.yml
    
    - name: Remove taints from the control node
      shell: |
        kubectl taint nodes --all node-role.kubernetes.io/control-plane-
    
      
