- name: Configure CNI network
  hosts: masters
  become: yes
  tasks:
    - name: Apply weave CNI plugin
      shell: |
        kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml 
      
    
    
      
