- hosts: masters
  become: yes
  tasks:
    - name: Add worker role to worker-node1
      command: kubectl label node worker-node1 node-role.kubernetes.io/worker=worker

    - name: Add worker role to worker-node2
      command: kubectl label node worker-node2 node-role.kubernetes.io/worker=worker