- hosts: masters
  become: yes
  tasks:
    - name: initialize K8S cluster
      shell: kubeadm init --pod-network-cidr=172.16.0.0/16 --apiserver-advertise-address=10.0.2.4

    - name: create .kube directory
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        remote_src: yes

    - name: install Pod network
      become: yes
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
    
    - name: add /usr/local/bin to PATH
      become: yes
      lineinfile:
        dest: /etc/profile
        line: 'export PATH="/usr/local/bin:$PATH"'
        insertafter: EOF
      environment:
        PATH: "/usr/local/bin:$PATH"

    - name: install Helm
      become: yes
      get_url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
