- hosts: masters
  become: yes
  tasks:     
    - name: Get MASTER_PRIVATE_IP
      shell: ip addr show enp0s3 | awk '/inet / {print $2}' | cut -d/ -f1
      register: MASTER_PRIVATE_IP_raw

    - name: Set MASTER_PRIVATE_IP
      set_fact:
        MASTER_PRIVATE_IP: "{{ MASTER_PRIVATE_IP_raw.stdout_lines[0] }}"

    - name: Get NODENAME
      shell: hostname -s
      register: NODENAME_raw

    - name: Set NODENAME
      set_fact:
        NODENAME: "{{ NODENAME_raw.stdout_lines[0] }}"

    - name: Pull config images
      shell: |
        kubeadm config images pull

    - name: Initialize kubeadm
      shell: kubeadm init --apiserver-advertise-address="{{ MASTER_PRIVATE_IP }}" --apiserver-cert-extra-sans="{{ MASTER_PRIVATE_IP }}" --pod-network-cidr="172.16.10.0/16" --node-name "{{ NODENAME }}" --ignore-preflight-errors Swap

    - name: Create .kube directory
      file:
        path: "~/.kube"
        state: directory

    - name: Copy admin.conf to .kube/config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "~/.kube/config"
        remote_src: yes
        mode: '0700'
    
    - name: Add KUBECONFIG to ~/.bashrc
        lineinfile:
          dest: ~/.bashrc
          line: "export KUBECONFIG=~/.kube/config"
          insertafter: EOF
          state: present
          create: yes
          
    - name: Set KUBECONFIG for the current shell session
      shell: export KUBECONFIG=~/.kube/config
    
    - name: Taint master node for scheduling apps
      shell: |
        kubectl taint nodes --all node-role.kubernetes.io/control-plane-
  
    - name: Download metrics server config
      get_url:
        url: "https://raw.githubusercontent.com/techiescamp/kubeadm-scripts/main/manifests/metrics-server.yaml"
        dest: /tmp/
        validate_certs: no

    - name: Run metrics server
      shell: |
        kubectl create -f /tmp/metrics-server.yaml