- hosts: masters
  become: yes
  tasks:
    - name: Pull config images
      shell: |
        kubeadm config images pull

    - name: Initialize kubeadm
      command: kubeadm init --apiserver-advertise-address="10.0.2.4" --apiserver-cert-extra-sans="10.0.2.4" --pod-network-cidr="172.16.10.0/16" --node-name "master-node" --ignore-preflight-errors Swap

    - name: Create .kube directory
      file:
        path: "~/.kube"
        state: directory

    - name: Copy admin.conf to .kube/config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "~/.kube/config"
        remote_src: yes
        mode: '0644'

    - name: Set ownership of .kube/config
      file:
        path: "~/.kube/config"
        owner: "root"
        mode: '0600'
    
    - name: Export KUBECONFIG
      set_fact:
        ansible_shell_env:
          KUBECONFIG: ~/.kube/config
    
    - name: Enable and start kubelet
      service: 
        name: kubelet
        enabled: yes
        state: started
    
    - name: Install calico network plugin
      shell: |
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/tigera-operator.yaml
      
    - name: Download custom resources config
      get_url:
        url: "https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/custom-resources.yaml"
        dest: /tmp/
        validate_certs: no

    - name: Apply custom resources
      shell: |
        kubectl create -f /tmp/custom-resources.yaml

    - name: Download metrics server config
      get_url:
        url: "https://raw.githubusercontent.com/techiescamp/kubeadm-scripts/main/manifests/metrics-server.yaml"
        dest: /tmp/
        validate_certs: no

    - name: Run metrics server
      shell: |
        kubectl create -f /tmp/metrics-server.yaml