- hosts: masters
  become: yes
  tasks:
    - name: Initialize kubeadm
      command: kubeadm init --pod-network-cidr=172.16.10.0/16 --service-cidr=10.96.0.0/12
      register: kubeadm_output

    - debug:
        var: kubeadm_output.stdout_lines

    - name: Create .kube directory
      file:
        path: "~/.kube"
        state: directory

    - name: Copy admin.conf to .kube/config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "~/.kube/config"
        remote_src: yes
        mode: '0644'

    - name: Set ownership of .kube/config
      file:
        path: "~/.kube/config"
        owner: "root"
        mode: '0600'
    
    - name: Export KUBECONFIG
      set_fact:
        ansible_shell_env:
          KUBECONFIG: ~/.kube/config
    
    - name: Enable and start kubelet
      service: 
        name: kubelet
        enabled: yes
        state: started
    
    - import_playbook: install-helm.yml
            
    - name: Install CNI network plugins binaries
      command: |
        mkdir -p /opt/cni/bin
        curl -O -L https://github.com/containernetworking/plugins/releases/download/v1.2.0/cni-plugins-linux-amd64-v1.2.0.tgz
        tar -C /opt/cni/bin -xzf cni-plugins-linux-amd64-v1.2.0.tgz

    - name: Apply flannel CNI
      command: |
        kubectl create ns kube-flannel
        kubectl label --overwrite ns kube-flannel pod-security.kubernetes.io/enforce=privileged
        helm repo add flannel https://flannel-io.github.io/flannel/
        helm install flannel --set podCidr="172.16.10.0/16" --namespace kube-flannel flannel/flannel
        