- name: Install Helm
  hosts: masters
  become: true

  tasks:
    - name: add /usr/local/bin to PATH
      lineinfile:
        dest: /etc/environment
        regexp: '^PATH='
        line: 'PATH="/usr/local/bin:/usr/bin:/bin"'
        state: present
        backup: yes
      notify: Reload shell

    - name: download Helm
      get_url:
        url: "https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz"
        dest: /tmp/
        validate_certs: no

    - name: unpack tar
      dunarchive:
        src: /tmp/helm-v3.12.0-linux-amd64.tar.gz
        dest: /tmp/
        remote_src: yes
        extra_opts: "-zxvf"
    
    - name: move helm to /usr/local/bin
      command:
        cmd: install -o root -g root -m 0755 /tmp/linux-64/helm /usr/local/bin/helm

  handlers:
    - name: Reload shell
      shell: source /etc/environment